version: "3.1"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./nginx/:/etc/nginx/
      - ../app/static/:/usr/share/nginx/html/static/
    networks:
      - nginx-load-balancer
      - stm
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
      - ../:/opt/stm
    networks:
      - stm
    restart: always
  mysql:
    image: mysql
    # This root password will be overwritten with the password used in
    # the backup that will be restored from a .sql file in the
    # docker-entrypoint-initdb.d directory. When starting a totally new
    # instance look in `docker-compose logs` for the line with
    # 'GENERATED ROOT PASSWORD:' to find the password and use it in
    # 'ETHERPAD_DB_PASSWORD' above and in backup.sh.
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    networks:
      - stm
    volumes:
      - stm-mysql-volume:/var/lib/mysql
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
networks:
  stm:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
volumes:
  stm-mysql-volume:
